[I 2025-09-24 09:52:03,368] A new study created in memory with name: xgb_gpu_tuning
[Optuna-XGB-GPU] Start tuning
  0%|          | 0/60 [00:00<?, ?it/s]                                        0%|          | 0/60 [00:00<?, ?it/s]                                        0%|          | 0/60 [00:00<?, ?it/s]  0%|          | 0/60 [00:00<?, ?it/s]
[W 2025-09-24 09:52:03,379] Trial 0 failed with parameters: {'n_estimators': 800, 'max_depth': 12, 'min_child_weight': 7.587945476302646, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.6624074561769746, 'gamma': 0.7799726016810132, 'reg_alpha': 0.2904180608409973, 'reg_lambda': 4.330880728874676, 'eta': 0.0798261175712336} because of the following error: TypeError("fit() got an unexpected keyword argument 'early_stopping_rounds'").
Traceback (most recent call last):
  File "/home/r3taker/miniconda3/envs/wine_mlops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/home/r3taker/Study/PMLDL/assignment_1/F25-PMLDL-Assignment-I/code/models/xgb_gpu_optuna.py", line 77, in objective
    model.fit(
  File "/home/r3taker/miniconda3/envs/wine_mlops/lib/python3.9/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
TypeError: fit() got an unexpected keyword argument 'early_stopping_rounds'
[W 2025-09-24 09:52:03,379] Trial 0 failed with value None.
Traceback (most recent call last):
  File "/home/r3taker/Study/PMLDL/assignment_1/F25-PMLDL-Assignment-I/code/models/xgb_gpu_optuna.py", line 154, in <module>
    main()
  File "/home/r3taker/Study/PMLDL/assignment_1/F25-PMLDL-Assignment-I/code/models/xgb_gpu_optuna.py", line 145, in main
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)
  File "/home/r3taker/miniconda3/envs/wine_mlops/lib/python3.9/site-packages/optuna/study/study.py", line 490, in optimize
    _optimize(
  File "/home/r3taker/miniconda3/envs/wine_mlops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/r3taker/miniconda3/envs/wine_mlops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial_id = _run_trial(study, func, catch)
  File "/home/r3taker/miniconda3/envs/wine_mlops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 258, in _run_trial
    raise func_err
  File "/home/r3taker/miniconda3/envs/wine_mlops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/home/r3taker/Study/PMLDL/assignment_1/F25-PMLDL-Assignment-I/code/models/xgb_gpu_optuna.py", line 77, in objective
    model.fit(
  File "/home/r3taker/miniconda3/envs/wine_mlops/lib/python3.9/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
TypeError: fit() got an unexpected keyword argument 'early_stopping_rounds'
